### ISSUE TITLE
Issues with Debian buster box

### ISSUE THREAD

**Issue by d78ui98** [fujimakishouten/vagrant-boxes#1]
I am using the new Debian buster box([fujimakishouten/debian-buster64](https://app.vagrantup.com/fujimakishouten/boxes/debian-buster64)). It is giving me this error when I do a `vagrant up`
```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

mount: /vagrant: unknown filesystem type 'vboxsf'.
```
I did a google search about it, None of the mentioned solutions worked
Virtualbox version `5.2.8r121009` 
Vagrant version `2.1.1`

**Comment by fujimaki-k** [comment]
Current version of VirtualBox in buster is 5.2.10-dfsg-6.
This version of VirtualBox has following bug.

> virtualbox-guest-dkms: vboxvideo module fails to build with 4.16 kernel
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=897928

I'm currently getting same error while building kernel module.
I think that the next version of VirtualBox resolve the bug.

Thank you for your reporting.

**Comment by d78ui98** [comment]
Thanks for the quick reply :)

Updating was my first step in resolving this issue.
I am using virtualbox version `5.2.12r122591`
I hope newer version solves this issue. But I think I found a
solution(or just a workaround). Users can install vagrant plugin
named `vagrant-vbguest` by
```
vagrant plugin install vagrant-vbguest
```
This checks and updates VirtualBox Guest Additions.
So my problem is resolved. We can close this issue

**Comment by fujimaki-k** [comment]
I created [trouble shooting page](https://github.com/fujimakishouten/vagrant-boxes/wiki/Trouble-shooting) in GitHub Wiki Page.
Thank you.
